docker:
  image: yegor256/rultor-image:1.9.1
release:
  script: |-
    date=$(date +%Y/%m/%d)
    sed -i "s|00\.00\.0000|${date}|" ffcode.sty
    sed -i "s/0\.0\.0/${tag}/g" ffcode.sty
    sed -i "s|00\.00\.0000|${date}|" ffcode.tex
    sed -i "s/0\.0\.0/${tag}/g" ffcode.tex
    sed -i "s/0\.0\.0/${tag}/g" build.lua
    make
    tlmgr install l3build
    l3build upload
