docker:
  image: yegor256/rultor-image:1.12.0
install: |-
  env
  tlmgr option repository ctan
  tlmgr --verify-repo=none update --self
  tlmgr --verify-repo=none install l3build
release:
  script: |-
    make VERSION=${tag} set-version
    git commit -m "version set to ${tag}"
    make
    l3build upload
