docker:
  image: yegor256/rultor-image:1.12.3
install: |-
  sudo apt install -y python3-pygments
  sudo pip3 install pygments
  sudo tlmgr option repository ctan
  sudo tlmgr --verify-repo=none update --self
  sudo tlmgr --verify-repo=none install l3build
  sudo tlmgr --verify-repo=none install libertine minted fvextra framed tcolorbox environ catchfile xstring xkeyval
release:
  script: |-
    make VERSION=${tag} set-version
    git commit -am "version set to ${tag}"
    make
    l3build upload
