name: l3build
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  l3build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: sudo apt-get install -y python3-pygments && sudo pip3 install pygments
        if: matrix.os == 'ubuntu-20.04'
      - run: |
          pip3 install --upgrade pip
          pip3 install pygments
          # easy_install Pygments
          pygmentize -V
        if: matrix.os == 'macos-12'
      - run: sudo apt-get -y install ghostscript
        if: matrix.os == 'ubuntu-20.04'
      - uses: teatimeguest/setup-texlive-action@v2.6.2
        with:
          update-all-packages: true
          package-file: DEPENDS.txt
      - run: l3build ctan --show-log-on-error --halt-on-error
      - uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: build/distrib/tds/tex/latex
          clean: true
        if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-20.04'
