name: l3build
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  l3build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: sudo apt-get install -y python3-pygments && sudo pip3 install pygments
        if: matrix.os == 'ubuntu-22.04'
      - run: |
          pip3 install --upgrade pip
          pip3 install pygments
          # easy_install Pygments
          pygmentize -V
        if: matrix.os == 'macos-12'
      - run: sudo apt-get -y install ghostscript
        if: matrix.os == 'ubuntu-22.04'
      - uses: teatimeguest/setup-texlive-action@v2.6.2
        with:
          update-all-packages: true
          package-file: DEPENDS.txt
      - run: l3build ctan --show-log-on-error --halt-on-error
      - run: |
          mkdir build/gh-pages
          cp build/distrib/tds/tex/latex/ffcode/ffcode.sty build/gh-pages
          sed -i "s/0\.0\.0/$(date +%H.%M.%S)/g" build/gh-pages/ffcode.sty
          sed -i "s/0000-00-00/$(date +%Y-%m-%d)/g" build/gh-pages/ffcode.sty
        if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-22.04'
      - uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: build/gh-pages
          clean: true
        if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-22.04'
