name: latexmk
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yegor256/latexmk-action@0.3.0
        with:
          opts: -pdf
          packages: libertine minted fvextra framed tcolorbox environ
