---
name: markdown-lint
on:
  push:
jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@43045ae669be728bd34ed56fcd1a230c0dc4d8e2
      - uses: articulate/actions-markdownlint@v1
