---
name: yamllint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  yamllint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
